// <auto-generated />
using System;
using K2PerfMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K2PerfMonitor.Data.Migrations
{
    [DbContext(typeof(MonitorDbContext))]
    [Migration("20260814145116_AddUsersAndInstances")]
    partial class AddUsersAndInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.AlertEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollectorType")
                        .HasColumnType("int");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastNotifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MetricValue")
                        .HasColumnType("float");

                    b.Property<int>("NotifyCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RaisedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("DedupKey", "Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.AlertRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Channels")
                        .HasColumnType("int");

                    b.Property<int>("CollectorType")
                        .HasColumnType("int");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("MetricField")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<double>("Threshold")
                        .HasColumnType("float");

                    b.Property<string>("TitleTemplate")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectorType", "Enabled");

                    b.ToTable("AlertRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Channels = 7,
                            CollectorType = 1,
                            CooldownMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "AvgDurationMs",
                            Name = "Slow Query (avg > 5s)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 5000.0
                        },
                        new
                        {
                            Id = 2L,
                            Channels = 7,
                            CollectorType = 1,
                            CooldownMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "AvgDurationMs",
                            Name = "Slow Query (avg > 15s)",
                            Operator = 0,
                            Severity = 2,
                            Threshold = 15000.0
                        },
                        new
                        {
                            Id = 3L,
                            Channels = 7,
                            CollectorType = 9,
                            CooldownMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "AvgDurationMs",
                            Name = "Slow Stored Proc (avg > 5s)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 5000.0
                        },
                        new
                        {
                            Id = 4L,
                            Channels = 7,
                            CollectorType = 3,
                            CooldownMinutes = 60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "WaitTimeMs",
                            Name = "High Wait Time",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 30000.0
                        },
                        new
                        {
                            Id = 5L,
                            Channels = 7,
                            CollectorType = 4,
                            CooldownMinutes = 15,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "BlockingDurationMs",
                            Name = "Long Blocking (> 30s)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 30000.0
                        },
                        new
                        {
                            Id = 6L,
                            Channels = 7,
                            CollectorType = 4,
                            CooldownMinutes = 15,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "BlockingDurationMs",
                            Name = "Severe Blocking (> 120s)",
                            Operator = 0,
                            Severity = 2,
                            Threshold = 120000.0
                        },
                        new
                        {
                            Id = 7L,
                            Channels = 7,
                            CollectorType = 8,
                            CooldownMinutes = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "CpuPercent",
                            Name = "High CPU (> 80%)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 80.0
                        },
                        new
                        {
                            Id = 8L,
                            Channels = 7,
                            CollectorType = 8,
                            CooldownMinutes = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "CpuPercent",
                            Name = "Critical CPU (> 95%)",
                            Operator = 0,
                            Severity = 2,
                            Threshold = 95.0
                        },
                        new
                        {
                            Id = 9L,
                            Channels = 7,
                            CollectorType = 8,
                            CooldownMinutes = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "AvailableMemoryMb",
                            Name = "Low Memory (< 512MB free)",
                            Operator = 2,
                            Severity = 1,
                            Threshold = 512.0
                        },
                        new
                        {
                            Id = 10L,
                            Channels = 7,
                            CollectorType = 8,
                            CooldownMinutes = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "AvailableMemoryMb",
                            Name = "Critical Memory (< 128MB free)",
                            Operator = 2,
                            Severity = 2,
                            Threshold = 128.0
                        },
                        new
                        {
                            Id = 11L,
                            Channels = 7,
                            CollectorType = 7,
                            CooldownMinutes = 60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "IoStallMsPerRead",
                            Name = "Slow I/O Read (> 20ms/op)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 20.0
                        },
                        new
                        {
                            Id = 12L,
                            Channels = 7,
                            CollectorType = 6,
                            CooldownMinutes = 360,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "MissingIndexImpact",
                            Name = "Missing Index (high impact)",
                            Operator = 0,
                            Severity = 0,
                            Threshold = 80.0
                        },
                        new
                        {
                            Id = 13L,
                            Channels = 7,
                            CollectorType = 10,
                            CooldownMinutes = 60,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "WorkflowDurationMs",
                            Name = "Stuck Workflow (> 24h)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 86400000.0
                        },
                        new
                        {
                            Id = 14L,
                            Channels = 7,
                            CollectorType = 11,
                            CooldownMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "FormLoadMs",
                            Name = "Slow Form Load (> 8s)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 8000.0
                        },
                        new
                        {
                            Id = 15L,
                            Channels = 7,
                            CollectorType = 12,
                            CooldownMinutes = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            MetricField = "SmartObjectCallMs",
                            Name = "Slow SmartObject Call (> 5s)",
                            Operator = 0,
                            Severity = 1,
                            Threshold = 5000.0
                        });
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.AppUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.BlockingEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlockedLoginName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BlockedQueryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlockedSessionId")
                        .HasColumnType("int");

                    b.Property<string>("BlockingLoginName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BlockingQueryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlockingSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedLockMode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Resource")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("WaitDurationMs")
                        .HasColumnType("float");

                    b.Property<string>("WaitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "BlockedSessionId");

                    b.ToTable("BlockingEvents", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.CollectorRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CollectorType")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double>("ElapsedMs")
                        .HasColumnType("float");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemsCollected")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("CollectorRuns", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.DeadlockEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlockAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeadlockGraphXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurvivorLoginName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurvivorQueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimLoginName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VictimProcessId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("VictimQueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("DeadlockAtUtc");

                    b.ToTable("DeadlockEvents", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.ExecutionPlanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgCpuMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgDurationMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgLogicalReads")
                        .HasColumnType("float");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ExecutionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanHandle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PlanXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("QueryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "QueryHash");

                    b.ToTable("ExecutionPlans", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.IndexRecommendationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EqualityColumns")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double>("Impact")
                        .HasColumnType("float");

                    b.Property<string>("IncludedColumns")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("IndexName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InequalityColumns")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendationScript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SchemaName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TableName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("UserLookups")
                        .HasColumnType("bigint");

                    b.Property<long>("UserScans")
                        .HasColumnType("bigint");

                    b.Property<long>("UserSeeks")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "RecommendationType");

                    b.ToTable("IndexRecommendations", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.IoStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BytesRead")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesWritten")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("IoStallMsPerRead")
                        .HasColumnType("float");

                    b.Property<double>("IoStallMsPerWrite")
                        .HasColumnType("float");

                    b.Property<double>("IoStallReadMs")
                        .HasColumnType("float");

                    b.Property<double>("IoStallWriteMs")
                        .HasColumnType("float");

                    b.Property<string>("LogicalFileName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("NumOfReads")
                        .HasColumnType("bigint");

                    b.Property<long>("NumOfWrites")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "DatabaseName");

                    b.ToTable("IoStats", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.K2SmartFormStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgLoadMs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double>("FormLoadMs")
                        .HasColumnType("float");

                    b.Property<string>("FormName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FormUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double?>("InitializeRuleMs")
                        .HasColumnType("float");

                    b.Property<long>("LoadCount")
                        .HasColumnType("bigint");

                    b.Property<double>("MaxLoadMs")
                        .HasColumnType("float");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "FormName");

                    b.ToTable("K2SmartFormStats", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.K2SmartObjectStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgDurationMs")
                        .HasColumnType("float");

                    b.Property<long>("CallCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("DurationMs")
                        .HasColumnType("float");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double>("MaxDurationMs")
                        .HasColumnType("float");

                    b.Property<string>("Method")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RowsReturned")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SmartObjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "SmartObjectName");

                    b.ToTable("K2SmartObjectStats", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.K2WorkflowStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CurrentActivityWaitMs")
                        .HasColumnType("float");

                    b.Property<double>("DurationMs")
                        .HasColumnType("float");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsStuck")
                        .HasColumnType("bit");

                    b.Property<string>("Originator")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProcInstId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcSetId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "Status");

                    b.ToTable("K2WorkflowStats", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.MonitoredInstanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("InstanceType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MonitoredInstances");
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.ServerStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveRequestCount")
                        .HasColumnType("int");

                    b.Property<double>("AvailableMemoryMb")
                        .HasColumnType("float");

                    b.Property<double>("BatchRequestsPerSec")
                        .HasColumnType("float");

                    b.Property<int>("BlockedProcessCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConnectionCount")
                        .HasColumnType("int");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("float");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double>("MemoryPercent")
                        .HasColumnType("float");

                    b.Property<int>("OnlineSchedulerCount")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("TotalMemoryMb")
                        .HasColumnType("float");

                    b.Property<long>("UptimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<double>("UsedMemoryMb")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.ToTable("ServerStats", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.ServerStatRollupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgBatchRequestsPerSec")
                        .HasColumnType("float");

                    b.Property<double>("AvgConnectionCount")
                        .HasColumnType("float");

                    b.Property<double>("AvgCpuPercent")
                        .HasColumnType("float");

                    b.Property<double>("AvgMemoryPercent")
                        .HasColumnType("float");

                    b.Property<int>("BucketMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("BucketStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxConnectionCount")
                        .HasColumnType("int");

                    b.Property<double>("MaxCpuPercent")
                        .HasColumnType("float");

                    b.Property<double>("MaxMemoryPercent")
                        .HasColumnType("float");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BucketMinutes", "BucketStartUtc")
                        .IsUnique();

                    b.ToTable("ServerStatRollups");
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.SlowQueryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgCpuMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgDurationMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgLogicalReads")
                        .HasColumnType("float");

                    b.Property<double>("AvgPhysicalReads")
                        .HasColumnType("float");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ExecutionCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastExecutionUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxDurationMs")
                        .HasColumnType("float");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanHandle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("TotalDurationMs")
                        .HasColumnType("float");

                    b.Property<double>("TotalLogicalReads")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "SourceKey");

                    b.ToTable("SlowQueries", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.StoredProcedureStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgElapsedMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgLogicalReads")
                        .HasColumnType("float");

                    b.Property<double>("AvgPhysicalReads")
                        .HasColumnType("float");

                    b.Property<double>("AvgWorkerMs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ExecutionCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastExecutionUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxElapsedMs")
                        .HasColumnType("float");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemaName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("TotalElapsedMs")
                        .HasColumnType("float");

                    b.Property<double>("TotalLogicalReads")
                        .HasColumnType("float");

                    b.Property<double>("TotalPhysicalReads")
                        .HasColumnType("float");

                    b.Property<double>("TotalWorkerMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "ObjectName");

                    b.ToTable("StoredProcedureStats", (string)null);
                });

            modelBuilder.Entity("K2PerfMonitor.Data.Entities.WaitStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBenign")
                        .HasColumnType("bit");

                    b.Property<double>("MaxWaitTimeMs")
                        .HasColumnType("float");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SignalWaitTimeMs")
                        .HasColumnType("float");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("WaitPercent")
                        .HasColumnType("float");

                    b.Property<double>("WaitTimeMs")
                        .HasColumnType("float");

                    b.Property<string>("WaitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("WaitingTasksCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CollectedAtUtc", "WaitType");

                    b.ToTable("WaitStats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
