<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-K2PerfMonitor.Worker-714132a6-4529-47ee-9b28-845038f341ca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Hangfire.NetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.*" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\K2PerfMonitor.Core\K2PerfMonitor.Core.csproj" />
    <ProjectReference Include="..\K2PerfMonitor.Data\K2PerfMonitor.Data.csproj" />
    <ProjectReference Include="..\K2PerfMonitor.Collectors\K2PerfMonitor.Collectors.csproj" />
    <ProjectReference Include="..\K2PerfMonitor.Alerts\K2PerfMonitor.Alerts.csproj" />
    <ProjectReference Include="..\K2PerfMonitor.Notifications\K2PerfMonitor.Notifications.csproj" />
    <ProjectReference Include="..\K2PerfMonitor.Realtime\K2PerfMonitor.Realtime.csproj" />
  </ItemGroup>
</Project>
