<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\K2PerfMonitor.Core\K2PerfMonitor.Core.csproj" />
    <ProjectReference Include="..\K2PerfMonitor.Data\K2PerfMonitor.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
